GET http://localhost:3000/
### 
GET http://localhost:3000/login
###
GET http://localhost:3000/signup

### 
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email" : "yongye0997@gmail.com",
    "password": "RateMyDine"
}