GET http://localhost:3000/
### 
GET http://localhost:3000/login
###
GET http://localhost:3000/signup

### 
POST http://localhost:3000/signup
Content-Type: application/json

{
    "email" : "yongye0997@gmail.com",
    "password": "RateMyDine"
}

### 
POST http://localhost:3000/login
Content-Type: application/json

{
    "LoginEmail" : "yongye0997@gmail.com",
    "LoinInPassword": "RateMyDine"
}
###
POST http://localhost:3000/signup
Content-Type: application/json

{
    "firstName": "jeff",
    "email" : "jeff@gmail.com",
    "password": "RateMyDine"
}

###
GET http://localhost:3000/review/300
