### 
POST http://localhost:3000/signup
Content-Type: application/json

{
    "firstName" : "Huggies",
    "lastName": "Hughug",
    "userName": "algebra2boy",
    "SignUpEmail": "yongyetan@umass.edu",
    "signUpPassword": "adamtranBest" 
}

### 
POST http://localhost:3000/signup
Content-Type: application/json

{
    "firstName" : "Jeff",
    "lastName": "Li",
    "userName": "zuki",
    "SignUpEmail": "jichengli@umass.edu",
    "signUpPassword": "sweetNMOre" 
}